### ISSUE TITLE
Shall we make this an official skeleton for DocPad?

### ISSUE THREAD

**Issue by balupton** [dstack/casper-skeleton#2]
Hey @dstack, do you plan on maintaining this long-term? If so, it would be great if this could be moved to https://github.com/docpad so we can open it up to the docpad extras team for small updates, and incorporate it in out test suites, you would maintain ownership. Let me know if you're interested in this.

**Comment by dstack** [comment]
Absolutely.  I'd love to have this be part of the official skeletons.  Let me know if there's anything else you need me to do to the repo or code.  Also, be advised, this is a direct port of Casper from Ghost, but nothing in the license said that it was explicitly for use with that platform, so there should be no license issues.

**Comment by balupton** [comment]
@dstack alright, you should have received an invitation to join the DocPad GitHub Organisation, once done, you will be able to transfer the repo to https://github.com/docpad via the repo settings. Let me know once done, and I'll add the rest of the extras team to the repo.

**Comment by dstack** [comment]
It's done..

**Comment by balupton** [comment]
Alrighty, renamed for convention, extras team added (you're a part of it), default branch changed to `docpad-6.x`, and docpad/extras `exchange.json` updated to note this is supported!

Yay! :+1: :dancer:
