### ISSUE TITLE
purpose of both isPost and active meta tags?

### ISSUE THREAD

**Issue by joshball** [dstack/casper-skeleton#4]
Hi,

I was curious what the purpose of having both `active` and `isPost` meta tags? 

I presume meta is skeleton specific (and opaque to docpad)? And therefore only used here:

```
@getCollection("html")
    .findAllLive({active:true, isPost: true, isPagedAuto: {$ne: true}}, {postDate: -1})
    .on "add", (model) -> model.setMetaDefaults({layout:"post"})
```

**Comment by dstack** [comment]
Hi @joshball , thanks for asking.

This is a feature I found personally usefull. I use this exact method (with a very early prototype of the Casper port) on my personal blog, and I have found some use out of having unpublished drafts.

Put simply, you can use `active: false` to easily turn off a post.  `isPost` is used for adding that specific page to the "posts" collection.  It's effectively the distinction between something that shows up in the blog-roll, and something that doesn't.

Now, you could argue that the same effect could be achieved by simply branching / tagging specific versions of your sites' codebase, however, I feel this does not account for the simpler, plausible use-case of someone who edits with docpad, but publishes via ftp, surge.sh, or any variety of deployment methods that don't involve or target git hashes.

You're not wrong.  From the perspective of the code, there's no difference.  I just see this as a simple way to temporarily eliminate a post without having to modify the codebase significantly.

**Comment by dstack** [comment]
To expand on the second part of your question: in general, meta is opaque to docpad and is specific to a skeleton.  There are a handful of meta tags that have significance to docpad, they are documented here http://docpad.org/docs/meta-data. `isPost` and `active` are not a part of that list.

**Comment by joshball** [comment]
Thanks @dstack, 
Thanks for the explanation. I was just uncertain if I had missed something in either docpad or ghost that I should have caught. Sounds like this is plenty straightforward. 
Nice work on the port, btw. Thank you.
